language: node_js
install:
    - npm install
node_js:
    - '10'
    - '14'
addons:
    chrome: stable
sudo: required
before_script:
    - 'sudo chown root /opt/google/chrome/chrome-sandbox'
    - 'sudo chown 4755 /opt/google/chrome/chrome-sandbox'
